/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


namespace zorba
{
namespace readpdf
{

/* Header for class CppOutputStreamCreator */

class CppOutputStreamCreator
{
  private:
    // Global reference to mirror java object CppOutputStreamCreator
    jobject _obj;
    // List of streams created by newOutputStream()
    std::vector<std::stringstream *> _ssVector;

    CppOutputStreamCreator()
    {}

    void setJavaObject(jobject jo)
    { _obj = jo; }

  public:
    ~CppOutputStreamCreator()
    {
        _obj = 0;
        for ( std::vector<std::stringstream *>::size_type i = 0; i<_ssVector.size(); i++)
        {
          delete _ssVector[i];
        }
    }

    static CppOutputStreamCreator* newInstance(JNIEnv * env);

    std::ostream* newOutputStream();

    int getSize()
    {
      return _ssVector.size();
    }

    jobject getJavaObject()
    { return _obj; }

    std::stringstream * getSS(int i)
    { return _ssVector[i]; }

    void close(JNIEnv * env);
};


}}; // namespace zorba, readpdf

#ifndef _Included_org_zorbaxquery_modules_readPdf_CppOutputStreamCreatorH
#define _Included_org_zorbaxquery_modules_readPdf_CppOutputStreamCreatorH

#ifdef WIN32
#  define DLL_EXPORT __declspec(dllexport)
#else
#  define DLL_EXPORT __attribute__ ((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif
#undef CppOutputStreamCreator_SKIP_BUFFER_SIZE
#define CppOutputStreamCreator_SKIP_BUFFER_SIZE 2048L

/*
 * Class:     CppOutputStreamCreator
 * Method:    nativeCreateNewOutputStream
 * Signature: ([BI)I
 */
JNIEXPORT jlong JNICALL DLL_EXPORT
Java_org_zorbaxquery_modules_readPdf_CppOutputStreamCreator_nativeCreateNewOutputStream
  (JNIEnv *, jobject, jlong p);

#ifdef __cplusplus
}
#endif
#endif //_Included_org_zorbaxquery_modules_readPdf_CppOutputStreamCreatorH
