/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OutputStreamToCpp */

#ifndef _Included_org_zorbaxquery_modules_readPdf_OUTPUTSTREAMTOCPP_H
#define _Included_org_zorbaxquery_modules_readPdf_OUTPUTSTREAMTOCPP_H

#ifdef WIN32
#  define DLL_EXPORT __declspec(dllexport)
#else
#  define DLL_EXPORT __attribute__ ((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif
#undef OutputStreamToCpp_SKIP_BUFFER_SIZE
#define OutputStreamToCpp_SKIP_BUFFER_SIZE 2048L

/*
 * Class:     OutputStreamToCpp
 * Method:    nativeWrite
 * Signature: ([BIIL)I
 */
JNIEXPORT jint JNICALL DLL_EXPORT
Java_org_zorbaxquery_modules_readPdf_OutputStreamToCpp_nativeWrite
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);


#ifdef __cplusplus
}
#endif

#endif // _Included_org_zorbaxquery_modules_readPdf_OUTPUTSTREAMTOCPP_H